### ISSUE TITLE
In Windows Process connector, retrieve the process user name and allow to select the process with user name

### ISSUE THREAD

**Issue by bertysentry** [sentrysoftware/metricshub-community-connectors#112]
# Use Case

Sometimes, the user a process runs as is a critical information to select a process to monitor. In the WindowsProcess connector, this information is not available.

# Specification

Retrieve the user each process runs as by querying `Win32_LoggedOnUser` .

ChatGPT's explanation:

1. **Win32_LoggedOnUser:** This WMI class links user accounts (`Win32_Account`) with the sessions they are logged into (`Win32_LogonSession`).
2. **Win32_Process**: This WMI class gives us details about processes, including their session ID (`SessionId`).
3. Joining Data: We first map session IDs to users by querying `Win32_LoggedOnUser`. Then, we match processes to users by comparing the `SessionId` from `Win32_Process` with our session-user map.

Then add a `keepOnlyMatchingLines` filter for the variable `${var::matchUser}`, and add attribute `process.match.user`.

**Comment by NassimBtk** [comment]
@bertysentry unfortunately, there is no WMI query that directly or indirectly relates `Win32_Process.SessionId` to `Win32_LogonSession`. 
It seems that the `GetOwner()` method on `Win32_Process` is the good approach to directly retrieve the account (user) that owns the process, without having to worry about `Win32_LogonSession.LogonId` and `Win32_Process.SessionId`.
Should we add the support for WMI Invoke Method queries?
