### ISSUE TITLE
Add temperature thresholds to MIB2EntitySensor

### ISSUE THREAD

**Issue by MarcDouguedroit** [sentrysoftware/metricshub-community-connectors#46]
This connector reports temperature readings but does not provide thresholds for these temperatures.

Check if it would be possible to add high.degraded and high.critical thresholds.

**Comment by NassimBtk** [comment]
ENTITY-SENSOR-MIB doesn't provide temperature thresholds. We are not going to invent new thresholds for the MIB2EntitySensor-header connector.
